languageCode: en-gb
baseUrl: "https://nurul9615.github.io/"
title: nurul9615.github.io
theme: PaperMod

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: nurul9615.github.io
  description: Brain Excretions
  keywords: [Blog, Nurul, PaperMod]
  author: Nurul
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true

  homeInfoParams:
    Title: Brain Excretions
    Content: |
      Build a man a fire, and he'll be warm for a day.

      Set a man on fire, and he'll be warm for the rest of his life.

  socialIcons:
    - name: github
      url: "https://github.com/nurul9615"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: search
      name: search
      url: /search/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 30

pygmentsUseClasses: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: false
    noClasses: false
    style: onedark

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
